version: '3'
services:
  app:
    environment:
    - WDS_SOCKET_HOST=127.0.0.1 
    - CHOKIDAR_USEPOLLING=true
    - WATCHPACK_POLLING=true 
    build: .
    volumes:
      - .:/app
    ports:
      - 3000:3000
    tty: true